### ISSUE TITLE
issues with dependencies. 

### ISSUE THREAD

**Issue by smohaus** [cozygene/glint#12]
How do I resolve this? I'm trying to run the tutorial. 

python glint.py --datafile datafile.txt --covarfile covariates.txt --phenofile phenotypes.txt --gsave
Validating all dependencies are installed...
All dependencies are installed
Traceback (most recent call last):
  File "/glint/glint.py", line 8, in <module>
    from utils import common
  File "/glint/utils/__init__.py", line 1, in <module>
    from argument_parser import  GlintArgumentParser
ModuleNotFoundError: No module named 'argument_parser'

**Comment by E-R** [comment]
Can you provide more details about your environment?
Did you try using a new conda environment with the exact dependencies specified in the README?

**Comment by Arsoy752** [comment]
> How do I resolve this? I'm trying to run the tutorial.
> 
> python glint.py --datafile datafile.txt --covarfile covariates.txt --phenofile phenotypes.txt --gsave Validating all dependencies are installed... All dependencies are installed Traceback (most recent call last): File "/glint/glint.py", line 8, in from utils import common File "/glint/utils/**init**.py", line 1, in from argument_parser import GlintArgumentParser ModuleNotFoundError: No module named 'argument_parser'

Hello I am having the same error did u manage to solve it

**Comment by E-R** [comment]
Did you try using a new conda environment with the exact dependencies specified in the README?

**Comment by Arsoy752** [comment]
Yes exactly as in README

**Comment by E-R** [comment]
This problem essentially means that python cannot find the argument_parser.py file which is in the utils directory. This can in principle be fixed by running `sys.path.insert(0, path_to_utils_directory)` however I would guess that if you see this problem then you are likely to then get errors with other imports from other files in other subdirectories; this can be to due a failure in the installation, which may result from deviations from the specific tested environment that we describe in the README (which cause the script to fail adding the directories of the codebase to the python path). Can you check if that's the case? If so try to similarly add the other directories to the path in the same way.
