### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by basharatbhat** [cozygene/glint#3]
- @

**Comment by E-R** [comment]
What are the dimensions of mvals.txt?
It doesn't look like a memory issue based on your free space, but it would still be a good idea to make sure that you can run the same command using a slimmer version of mvals.txt (so, e.g., head -n 10 mvals.txt > mvals_slim.txt, and then use mvals_slim.txt as the data file). 
Also, can you please add "--loglevel debug" to your command?

**Comment by basharatbhat** [comment]
Dimension of mvals.txt: I have 1000 epic array samples.
For small dataset ~50samples scripts are working fine.
Log file is attached: 
[glint.log](https://github.com/cozygene/glint/files/2874568/glint.log)

**Comment by E-R** [comment]
I couldn't replicate your error - I could run '--gsave' on a data file with 1000 epic samples (~850K rows) without a problem on a 16G machine.

Is it possible that you are using a machine that restricts your user memory usage for some reason?
Since I'm assuming you cannot link me to the data, can you try using a different machine?

**Comment by E-R** [comment]
I will wait a few more days for a response before closing this issue.
